# Generated by Django 5.2.2 on 2025-06-08 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destino", models.CharField(max_length=100)),
                ("accion", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
